### ISSUE TITLE
The site's down?

### ISSUE THREAD

**Issue by damianpeterson** [AltTracker/alttracker#12]
Seems the site's been down for a few days now and I don't see where else or who else to ask what's happening. Any news? It's a handy tool.

**Comment by Secretmapper** [comment]
Hello!

Sorry about this! The site is not down, but I've recently changed servers and unfortunately the domain has a DNS problem.

For now, you can access the site at http://69.30.241.246 I'm expecting it to be accessible again at alt tracker.com by today or tomorrow

**Comment by damianpeterson** [comment]
Oh nice one. Thanks for the link. Great work BTW.

**Comment by Secretmapper** [comment]
Thank you for the kind words!

I've just checked support with my registrar. Apparently, there was a one-time glitch in their server which caused the DNS not to update! They since then updated it, so hopefully it will go back up soon!
