### ISSUE TITLE
Values still rarely updated

### ISSUE THREAD

**Issue by nicolas-t** [AltTracker/alttracker#6]
Hello

I saw this [commit](https://github.com/AltTracker/alttracker/commit/afeed173f5b5b0ad73af5a65b0e6ec08fe29679e), but values still don't get updated more than once a day it seems.

Best,

**Comment by Secretmapper** [comment]
Thanks for the alert @nicolas-t 

From the logs, it seems that it does update every 5 minutes. Timestamps:

```
13:04:30 -
13:09:30 -
13:14:31 - 
```

I will look into it though and see if there's still a bug.

**Comment by stoyicker** [comment]
Just a follow-up: they do not seem to be updating at all for me for around a week already, if not longer.

**Comment by YoItsJoel** [comment]
Just thought I would throw in that I've also been experiencing this.  The tracker will update once a day sometimes, and normally other times.  Currently my coins have been saying the same price for just over 2 days.

**Comment by joel2762** [comment]
Same problem here. Ours are not showing as updated since Aug 2, is the last date showing on the graph.. It's stuck.

**Comment by stoyicker** [comment]
Updated for me as of now

**Comment by joel2762** [comment]
Mine updated that day (Aug 7) as well but that was it.. since then, back to no updates.

**Comment by Secretmapper** [comment]
I'm looking into this again. Weirdly enough, the logs does say it updates, and it does update if I reboot the server.

**Comment by stoyicker** [comment]
Yeah I'm seeing more frequent updates lately, so can corroborate that the reboots (I guess) have some effect. I don't know how this framework works, but if it helps, since the logs don't match reality, I would go with updates possibly not triggering a ui refresh.

**Comment by stevesbrain** [comment]
Can confirm mine also update maybe only once per day (sorry I don't have more helpful info than that, but just confirming it affects another human :) )

**Comment by Secretmapper** [comment]
I just fixed this!

Sorry for the inconvenience! This has been a big thorn I know!
